// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbWX2GoDmKmcsZQFQd2Bo1bkVkVHr_hvU',
    appId: '1:16815954149:web:142c5f885f42e866845c0c',
    messagingSenderId: '16815954149',
    projectId: 'infant-app-6ba73',
    authDomain: 'infant-app-6ba73.firebaseapp.com',
    databaseURL: 'https://infant-app-6ba73-default-rtdb.firebaseio.com',
    storageBucket: 'infant-app-6ba73.firebasestorage.app',
    measurementId: 'G-37N7VZ5D1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4cQxLB-TPu3tGFYNdMjcMYP4K-eOmCaw',
    appId: '1:16815954149:android:9d5c4030edc30ca3845c0c',
    messagingSenderId: '16815954149',
    projectId: 'infant-app-6ba73',
    databaseURL: 'https://infant-app-6ba73-default-rtdb.firebaseio.com',
    storageBucket: 'infant-app-6ba73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8JkqHq4d9oUymvrrhKWmWu8_NDX6thWk',
    appId: '1:16815954149:ios:d127735eedc82544845c0c',
    messagingSenderId: '16815954149',
    projectId: 'infant-app-6ba73',
    storageBucket: 'infant-app-6ba73.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8JkqHq4d9oUymvrrhKWmWu8_NDX6thWk',
    appId: '1:16815954149:ios:d127735eedc82544845c0c',
    messagingSenderId: '16815954149',
    projectId: 'infant-app-6ba73',
    storageBucket: 'infant-app-6ba73.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbWX2GoDmKmcsZQFQd2Bo1bkVkVHr_hvU',
    appId: '1:16815954149:web:f587600419437f1b845c0c',
    messagingSenderId: '16815954149',
    projectId: 'infant-app-6ba73',
    authDomain: 'infant-app-6ba73.firebaseapp.com',
    databaseURL: 'https://infant-app-6ba73-default-rtdb.firebaseio.com',
    storageBucket: 'infant-app-6ba73.firebasestorage.app',
    measurementId: 'G-9BV2TZ2V4D',
  );

}