// app_strings.dart — Lightweight i18n string map
// Screens read strings via AppStrings.t(key) using the current languageNotifier locale.


import 'package:first_app/main.dart' show languageNotifier;

class AppStrings {
  AppStrings._();

  // Active language code (defaults to 'en')
  static String get _lang => languageNotifier.value.languageCode;

  static String t(String key) {
    final lang = _lang;
    return _strings[lang]?[key] ?? _strings['en']![key] ?? key;
  }

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      // ── Dashboard ──────────────────────────────────────────────
      'greeting_morning':    'Good Morning,',
      'greeting_afternoon':  'Good Afternoon,',
      'greeting_evening':    'Good Evening,',
      'greeting_suffix':     "'s Caregiver",
      'infant_monitoring':   'Infant Monitoring',
      'vital_alert_active':  'Vital Alert Active',
      'all_vitals_normal':   'All Vitals Normal',
      'check_readings':      'Check readings immediately!',
      'vitals_safe':         "Baby's vitals are within safe range.",
      'excellent':           'Excellent',
      'good':                'Good',
      'fair':                'Fair',
      'poor':                'Poor',
      'heart_rate':          'Heart Rate',
      'body_temperature':    'Body Temperature',
      'oxygen_saturation':   'Oxygen Saturation',
      'updated':             'Updated',
      'updating':            'Updating…',
      'normal':              'Normal',
      'health_score_info':   'Health Score',
      'health_score_desc':   'The score is calculated from 3 vitals:\n\n• Heart Rate (−20 pts if critical, −5 pts if warning)\n• Temperature (−20 pts if > 38.5°C, −10 pts if > 38°C)\n• SpO₂ (−30 pts if < 89%, −15 pts if < 94%)\n\nA score of 90–100 = Excellent. 75–89 = Good. 50–74 = Fair. Below 50 = Poor.',
      'close':               'Close',

      // ── History ─────────────────────────────────────────────────
      'vitals_history':      'Vitals History',
      'historical_trends':   'Historical trends & data points',
      'export':              'Export',
      'export_title':        'Export Vitals Data',
      'export_csv':          'Export as CSV',
      'export_pdf':          'Export as PDF',
      'add_note':            'Add Note',
      'note_placeholder':    'e.g. after feeding',
      'save':                'Save',
      'cancel':              'Cancel',
      'notes':               'Notes',
      'point':               'Point',
      'h24':                 '24 Hours',
      'd7':                  '7 Days',
      'd30':                 '30 Days',
      'min':                 'Min',
      'avg':                 'Avg',
      'max':                 'Max',

      // ── Alerts ──────────────────────────────────────────────────
      'alerts':              'Alerts',
      'active_alerts':       'Active Alerts',
      'resolved_alerts':     'Resolved Alerts',
      'dismiss_all':         'Dismiss All',
      'dismiss':             'Dismiss',
      'snooze':              'Snooze',
      'threshold':           'Threshold',
      'no_resolved':         'No resolved alerts yet',
      'calm_message':        'Baby has been calm for',
      'calm_hours':          'hours',
      'calm_emoji':          '🎉',
      'custom_thresholds':   'Custom Alert Thresholds',
      'hr_min':              'Heart Rate Min (BPM)',
      'hr_max':              'Heart Rate Max (BPM)',
      'temp_max':            'Temperature Max',
      'spo2_min':            'SpO₂ Min (%)',
      'apply':               'Apply',
      'alert_dismissed':     'Alert dismissed',
      'all_dismissed':       'All alerts dismissed',
      'snoozed_for':         'Snoozed for',
      'minutes':             'min',
      'critical':            'CRITICAL',
      'warning':             'WARNING',
      'active_count':        'active',
      'resolved_count':      'resolved',

      // ── Profile ─────────────────────────────────────────────────
      'profile':             'Profile',
      'caregiver_info':      'Caregiver info',
      'infant_profile':      'Infant Profile',
      'caregiver_profile':   'Caregiver Profile',
      'growth_tracker':      'Growth Tracker',
      'weight_over_time':    'Weight & Height Over Time',
      'add':                 'Add',
      'monitoring_summary':  'Monitoring Summary',
      'days_monitored':      'Days Monitored',
      'alerts_triggered':    'Alerts Triggered',
      'avg_heart_rate':      'Avg Heart Rate',
      'last_checkup':        'Last Checkup',
      'next_checkup':        'Next Checkup',
      'not_scheduled':       'Not scheduled',
      'vaccination_tracker': 'Vaccination Tracker',
      'vaccinations':        'Vaccinations',
      'alert_breakdown':     'Alert Breakdown',
      'no_alerts_recorded':  'No alerts recorded yet.',
      'date':                'Date',
      'type':                'Type',
      'weight_kg':           'Weight (kg)',
      'height_cm':           'Height (cm)',
      'add_growth_entry':    'Add Growth Entry',
      'profile_updated':     'Profile updated successfully',

      // ── Settings ────────────────────────────────────────────────
      'settings':              'Settings',
      'preferences_notif':     'Preferences · Notifications · About',
      'notifications':         'Notifications',
      'push_notifications':    'Push Notifications',
      'sound_alerts':          'Sound Alerts',
      'vibration':             'Vibration',
      'preferences':           'Preferences',
      'dark_mode':             'Dark Mode',
      'temperature_unit':      'Temperature Unit',
      'language':              'Language',
      'data_refresh_rate':     'Data Refresh Rate',
      'battery_saver':         'Battery Saver Mode',
      'battery_saver_sub':     'Slows refresh to every 30 s',
      'cloud_backup':          'Cloud Backup / Sync',
      'cloud_backup_sub':      'Sync data to cloud automatically',
      'cloud_enabled':         'Cloud sync enabled — data will be backed up',
      'cloud_disabled':        'Cloud sync disabled',
      'settings_saved':        'Settings saved',
      'about':                 'About',
      'app_name':              'IoT Infant Vitals Monitor',
      'version':               'Version 1.0.0',
      'app_desc':              'A wearable IoT-based system for real-time monitoring of infant heart rate, body temperature, and oxygen saturation levels.',
      'log_out':               'Log Out',
      'sos':                   'SOS',
      'emergency_sos':         'Emergency SOS',
      'emergency_contact':     'Emergency Contact',
      'call_emergency':        'Call emergency services or contact your emergency contact immediately.',
    },

    'sw': {
      // ── Dashboard ──────────────────────────────────────────────
      'greeting_morning':    'Habari za Asubuhi,',
      'greeting_afternoon':  'Habari za Mchana,',
      'greeting_evening':    'Habari za Jioni,',
      'greeting_suffix':     ' — Mlezi',
      'infant_monitoring':   'Ufuatiliaji wa Mtoto',
      'vital_alert_active':  'Tahadhari ya Dalili',
      'all_vitals_normal':   'Dalili Zote Ziko Sawa',
      'check_readings':      'Angalia masomaji mara moja!',
      'vitals_safe':         'Dalili za mtoto ziko ndani ya kiwango salama.',
      'excellent':           'Bora',
      'good':                'Nzuri',
      'fair':                'Wastani',
      'poor':                'Mbaya',
      'heart_rate':          'Kiwango cha Moyo',
      'body_temperature':    'Joto la Mwili',
      'oxygen_saturation':   'Mzingatio wa Oksijeni',
      'updated':             'Imesasishwa',
      'updating':            'Inasasisha…',
      'normal':              'Kawaida',
      'health_score_info':   'Alama ya Afya',
      'health_score_desc':   'Alama inakokotolewa kutoka kwa dalili 3:\n\n• Kiwango cha Moyo (−20 ikiwa muhimu)\n• Joto (−20 ikiwa > 38.5°C)\n• SpO₂ (−30 ikiwa < 89%)\n\n90–100 = Bora. 75–89 = Nzuri. 50–74 = Wastani.',
      'close':               'Funga',
      // ── History ─────────────────────────────────────────────────
      'vitals_history':      'Historia ya Dalili',
      'historical_trends':   'Mwenendo wa kihistoria',
      'export':              'Hamisha',
      'export_title':        'Hamisha Data ya Dalili',
      'export_csv':          'Hamisha kama CSV',
      'export_pdf':          'Hamisha kama PDF',
      'add_note':            'Ongeza Kumbukumbu',
      'note_placeholder':    'mfano. baada ya kulisha',
      'save':                'Hifadhi',
      'cancel':              'Ghairi',
      'notes':               'Kumbukumbu',
      'point':               'Nukta',
      'h24':                 'Masaa 24',
      'd7':                  'Siku 7',
      'd30':                 'Siku 30',
      'min':                 'Kiwango',
      'avg':                 'Wastani',
      'max':                 'Juu',
      // ── Alerts ──────────────────────────────────────────────────
      'alerts':              'Tahadhari',
      'active_alerts':       'Tahadhari Hai',
      'resolved_alerts':     'Tahadhari Zilizosuluhiwa',
      'dismiss_all':         'Futa Zote',
      'dismiss':             'Futa',
      'snooze':              'Ahirisha',
      'threshold':           'Kiwango Cha Mwisho',
      'no_resolved':         'Hakuna tahadhari zilizosuluhiwa bado',
      'calm_message':        'Mtoto amekuwa na utulivu kwa',
      'calm_hours':          'masaa',
      'calm_emoji':          '🎉',
      'custom_thresholds':   'Viwango Maalum vya Tahadhari',
      'hr_min':              'Kiwango cha Moyo Min (BPM)',
      'hr_max':              'Kiwango cha Moyo Max (BPM)',
      'temp_max':            'Joto Max',
      'spo2_min':            'SpO₂ Min (%)',
      'apply':               'Tumia',
      'alert_dismissed':     'Tahadhari imefutwa',
      'all_dismissed':       'Tahadhari zote zimefutwa',
      'snoozed_for':         'Imahiriwa kwa',
      'minutes':             'dak',
      'critical':            'MUHIMU',
      'warning':             'ONYO',
      'active_count':        'hai',
      'resolved_count':      'zilizosuluhiwa',
      // ── Profile ─────────────────────────────────────────────────
      'profile':             'Wasifu',
      'caregiver_info':      'Taarifa za Mlezi',
      'infant_profile':      'Wasifu wa Mtoto',
      'caregiver_profile':   'Wasifu wa Mlezi',
      'growth_tracker':      'Ufuatiliaji wa Ukuaji',
      'weight_over_time':    'Uzito na Urefu kwa Wakati',
      'add':                 'Ongeza',
      'monitoring_summary':  'Muhtasari wa Ufuatiliaji',
      'days_monitored':      'Siku Zilizofuatiliwa',
      'alerts_triggered':    'Tahadhari Zilizotolewa',
      'avg_heart_rate':      'Wastani wa Moyo',
      'last_checkup':        'Uchunguzi wa Mwisho',
      'next_checkup':        'Uchunguzi Ujao',
      'not_scheduled':       'Haijapangwa',
      'vaccination_tracker': 'Ufuatiliaji wa Chanjo',
      'vaccinations':        'Chanjo',
      'alert_breakdown':     'Maelezo ya Tahadhari',
      'no_alerts_recorded':  'Hakuna tahadhari zilizorekodiwa bado.',
      'date':                'Tarehe',
      'type':                'Aina',
      'weight_kg':           'Uzito (kg)',
      'height_cm':           'Urefu (cm)',
      'add_growth_entry':    'Ongeza Rekodi ya Ukuaji',
      'profile_updated':     'Wasifu umesasishwa',
      // ── Settings ────────────────────────────────────────────────
      'settings':              'Mipangilio',
      'preferences_notif':     'Mapendeleo · Arifa · Kuhusu',
      'notifications':         'Arifa',
      'push_notifications':    'Arifa za Push',
      'sound_alerts':          'Arifa za Sauti',
      'vibration':             'Mtetemo',
      'preferences':           'Mapendeleo',
      'dark_mode':             'Hali ya Giza',
      'temperature_unit':      'Kipimo cha Joto',
      'language':              'Lugha',
      'data_refresh_rate':     'Kiwango cha Kusasisha Data',
      'battery_saver':         'Hali ya Kuokoa Betri',
      'battery_saver_sub':     'Kupunguza usasishaji hadi sekunde 30',
      'cloud_backup':          'Hifadhi ya Wingu / Ulandanishi',
      'cloud_backup_sub':      'Landanisha data kwenye wingu kiotomatiki',
      'cloud_enabled':         'Ulandanishi wa wingu umewezeshwa',
      'cloud_disabled':        'Ulandanishi wa wingu umezimwa',
      'settings_saved':        'Mipangilio imehifadhiwa',
      'about':                 'Kuhusu',
      'app_name':              'Kifuatiliaji cha Dalili za Mtoto',
      'version':               'Toleo 1.0.0',
      'app_desc':              'Mfumo wa IoT unaoweza kuvaliwa kwa ufuatiliaji wa wakati halisi wa mapigo ya moyo, joto la mwili, na mzingatio wa oksijeni wa mtoto.',
      'log_out':               'Toka',
      'sos':                   'SOS',
      'emergency_sos':         'Dharura SOS',
      'emergency_contact':     'Mawasiliano ya Dharura',
      'call_emergency':        'Piga simu huduma za dharura au wasiliana na anayehusika haraka.',
    },

    'fr': {
      // ── Dashboard ──────────────────────────────────────────────
      'greeting_morning':    'Bonjour,',
      'greeting_afternoon':  'Bon après-midi,',
      'greeting_evening':    'Bonsoir,',
      'greeting_suffix':     " — Accompagnateur",
      'infant_monitoring':   'Surveillance du Nourrisson',
      'vital_alert_active':  'Alerte de Constante Active',
      'all_vitals_normal':   'Toutes les Constantes Normales',
      'check_readings':      'Vérifiez les mesures immédiatement !',
      'vitals_safe':         'Les constantes du bébé sont dans la plage normale.',
      'excellent':           'Excellent',
      'good':                'Bon',
      'fair':                'Moyen',
      'poor':                'Mauvais',
      'heart_rate':          'Fréquence Cardiaque',
      'body_temperature':    'Température Corporelle',
      'oxygen_saturation':   'Saturation en Oxygène',
      'updated':             'Mis à jour',
      'updating':            'Mise à jour…',
      'normal':              'Normal',
      'health_score_info':   'Score de Santé',
      'health_score_desc':   'Le score est calculé à partir de 3 constantes :\n\n• Fréquence cardiaque (−20 pts si critique)\n• Température (−20 pts si > 38,5°C)\n• SpO₂ (−30 pts si < 89%)\n\n90–100 = Excellent. 75–89 = Bon. 50–74 = Moyen.',
      'close':               'Fermer',
      // ── History ─────────────────────────────────────────────────
      'vitals_history':      'Historique des Constantes',
      'historical_trends':   'Tendances historiques & données',
      'export':              'Exporter',
      'export_title':        'Exporter les Données',
      'export_csv':          'Exporter en CSV',
      'export_pdf':          'Exporter en PDF',
      'add_note':            'Ajouter une Note',
      'note_placeholder':    'ex. après la tétée',
      'save':                'Enregistrer',
      'cancel':              'Annuler',
      'notes':               'Notes',
      'point':               'Point',
      'h24':                 '24 Heures',
      'd7':                  '7 Jours',
      'd30':                 '30 Jours',
      'min':                 'Min',
      'avg':                 'Moy',
      'max':                 'Max',
      // ── Alerts ──────────────────────────────────────────────────
      'alerts':              'Alertes',
      'active_alerts':       'Alertes Actives',
      'resolved_alerts':     'Alertes Résolues',
      'dismiss_all':         'Tout Ignorer',
      'dismiss':             'Ignorer',
      'snooze':              'Répéter',
      'threshold':           'Seuil',
      'no_resolved':         'Aucune alerte résolue',
      'calm_message':        'Bébé est calme depuis',
      'calm_hours':          'heures',
      'calm_emoji':          '🎉',
      'custom_thresholds':   'Seuils d\'Alerte Personnalisés',
      'hr_min':              'FC Min (BPM)',
      'hr_max':              'FC Max (BPM)',
      'temp_max':            'Temp Max',
      'spo2_min':            'SpO₂ Min (%)',
      'apply':               'Appliquer',
      'alert_dismissed':     'Alerte ignorée',
      'all_dismissed':       'Toutes les alertes ignorées',
      'snoozed_for':         'Répété pour',
      'minutes':             'min',
      'critical':            'CRITIQUE',
      'warning':             'AVERTISSEMENT',
      'active_count':        'actives',
      'resolved_count':      'résolues',
      // ── Profile ─────────────────────────────────────────────────
      'profile':             'Profil',
      'caregiver_info':      'Infos accompagnateur',
      'infant_profile':      'Profil du Nourrisson',
      'caregiver_profile':   'Profil de l\'Accompagnateur',
      'growth_tracker':      'Suivi de Croissance',
      'weight_over_time':    'Poids & Taille dans le Temps',
      'add':                 'Ajouter',
      'monitoring_summary':  'Résumé de Surveillance',
      'days_monitored':      'Jours Surveillés',
      'alerts_triggered':    'Alertes Déclenchées',
      'avg_heart_rate':      'FC Moyenne',
      'last_checkup':        'Dernier Bilan',
      'next_checkup':        'Prochain Bilan',
      'not_scheduled':       'Non planifié',
      'vaccination_tracker': 'Suivi des Vaccinations',
      'vaccinations':        'Vaccinations',
      'alert_breakdown':     'Détail des Alertes',
      'no_alerts_recorded':  'Aucune alerte enregistrée.',
      'date':                'Date',
      'type':                'Type',
      'weight_kg':           'Poids (kg)',
      'height_cm':           'Taille (cm)',
      'add_growth_entry':    'Ajouter une Entrée',
      'profile_updated':     'Profil mis à jour',
      // ── Settings ────────────────────────────────────────────────
      'settings':              'Paramètres',
      'preferences_notif':     'Préférences · Notifications · À propos',
      'notifications':         'Notifications',
      'push_notifications':    'Notifications Push',
      'sound_alerts':          'Alertes Sonores',
      'vibration':             'Vibration',
      'preferences':           'Préférences',
      'dark_mode':             'Mode Sombre',
      'temperature_unit':      'Unité de Température',
      'language':              'Langue',
      'data_refresh_rate':     'Taux d\'Actualisation',
      'battery_saver':         'Mode Économie de Batterie',
      'battery_saver_sub':     'Ralentit l\'actualisation à 30 s',
      'cloud_backup':          'Sauvegarde Cloud / Sync',
      'cloud_backup_sub':      'Synchroniser les données automatiquement',
      'cloud_enabled':         'Synchronisation cloud activée',
      'cloud_disabled':        'Synchronisation cloud désactivée',
      'settings_saved':        'Paramètres enregistrés',
      'about':                 'À Propos',
      'app_name':              'Moniteur de Constantes Nourrisson IoT',
      'version':               'Version 1.0.0',
      'app_desc':              'Système IoT portable pour la surveillance en temps réel de la fréquence cardiaque, de la température et de la saturation en oxygène du nourrisson.',
      'log_out':               'Déconnexion',
      'sos':                   'SOS',
      'emergency_sos':         'SOS Urgence',
      'emergency_contact':     'Contact d\'Urgence',
      'call_emergency':        'Appelez les services d\'urgence ou contactez votre contact d\'urgence immédiatement.',
    },
  };
}
